export default [
  {
    id: 0,
    type: "intro",
    speakerInfo: null,
    timeline: [0, 1.5],
    text: {
      ipaText: "Dì|èr|kè|: |tīng |hé |huídá",
      targetLangText: "第|二|课|: |听|和|回答",
      translationText: "Lesson 2: Listen and Answer",
    },
    img: "/public/liming.jpeg",
    colors: null,
  },
  {
    id: 1,
    type: "narrative",
    speakerInfo: null,
    timeline: [1.5, 3],
    text: {
      ipaText: "`Dīng dōng`| - |ménlíng |xiǎng|le",
      targetLangText: "`叮咚`| - |门铃|响|了",
      translationText: "`Ding Dong` - the doorbell rang",
    },
    img: "",
    colors: null,
  },
  {
    id: 2,
    type: "question",
    speakerInfo: null,
    timeline: [3, 5],
    text: {
      ipaText: "Ménlíng |xiǎng |le |ma|?",
      targetLangText: "门铃|响|了|吗|?",
      translationText: "Did the doorbell ring?",
    },
    img: "",
    colors: null,
  },
  {
    id: 3,
    type: "answer",
    speakerInfo: null,
    timeline: [5, 7],
    text: {
      ipaText: "Duì|, |ménlíng |xiǎng |le",
      targetLangText: "对|,|门铃|响|了",
      translationText: "Correct, the doorbell rang",
    },
    img: "",
    colors: null,
  },
  {
    id: 4,
    type: "dialogue",
    speakerInfo: {
      avatar: "/public/liming.jpeg",
      ipaName: "Tiánzhōng",
      targetLangName: "田中",
    },
    timeline: [0, 3.459],
    text: {
      ipaText: "Nǐmen |hǎo|!",
      targetLangText: "你们|好|!",
      translationText: "Tanaka: Hello guys!",
    },
    img: "",
    colors: ["bg-neutral-400", "text-neutral-800"],
  },
];
